org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
mod_id=zstdnet
mod_name=ZstdNet
mod_group=mys.zstdnet.reborn
mod_version=1.1.7.2-beta
neoforge_1211_mod_version=1.1.7.2-beta
minecraft_version=1.21.1
java_version=21
zstd_jni_version=1.5.7-7
junit_version=5.10.2
architectury_loom_version=1.14.476
architectury_api_version=13.0.11
neoforge_version=21.1.223
neoforge_fml_loader_version=4.0.42
client_loom_enabled=true
fabric_loom_enabled=false
named_client_jar_enabled=false
neoforge_variant=1_21_1
