pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = "https://maven.neoforged.net/releases/" }
        maven { url = "https://api.modrinth.com/maven" }
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url = "https://libraries.minecraft.net/" }
        maven { url = "https://maven.neoforged.net/releases/" }
    }
}

rootProject.name = "ZstdNet"
