modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
description = '''
ZSTD network codec for ZstdNet NeoForge ${minecraft_version} servers and clients.
'''

[[mixins]]
config = "zstdnet.mixins.json"

[[mixins]]
config = "zstdnet-1_21_1.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"
